# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lil' Debbie's Coyote Grill
description: > # this means to ignore newlines until "baseurl:"
  Popular bar located in downtown Whitewater. Home of the best burger in Walworth county!
author: Jacob Mischka <jacob@coyotegrill.bar> (http://www.mischka.me)
keywords:
  - Coyote Grill
  - Lil' Debbie
  - Salvo
  - Burger
  - Cheeseburger
  - Whitewater
  - Wisconsin
  - Walworth county
  - Warhawks
  - College bar
  - Bar and grill
  - To-go
  - Takeout

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.coyotegrill.bar" # the base hostname & protocol for your site
phone: "262 472 0510"
address: "132 W. Center St, Whitewater WI"
email: contact@coyotegrill.bar

media:
  small_mobile: 600px
  small_desktop: 768px
  medium_desktop: 992px
  large_desktop: 1200px


# Build settings
markdown: kramdown
permalink: pretty
sass:
  style: compressed
exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - package.json
  - rollup.config.js
  - webpack.config.js

collections:
  - specials
  - nightly_specials
  - sections

defaults:
  - scope:
      path: ""
    values:
      layout: "page"

  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

  - scope:
      path: ""
      type: specials
    values:
      layout: special

  - scope:
      path: ""
      type: nightly_specials
    values:
      layout: nightly-special

gems:
  - jekyll-autoprefixer

autoprefixer:
  only_production: true
